; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_g431kb_usb_gamepad

[env:nucleo_g431kb]
platform = ststm32
board = nucleo_g431kb
framework = arduino
monitor_speed = 115200
upload_protocol = stlink

[env:nucleo_g431kb_usb_gamepad]
platform = ststm32
board = nucleo_g431kb
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
build_flags =
    -D DIY_WHEEL_NATIVE_GAMEPAD
    -D USBCON
    -D HAL_PCD_MODULE_ENABLED
    -D USBD_USE_HID_COMPOSITE
    -D USBD_CUSTOMHID_CTRL_REQ_GET_REPORT_ENABLED
    -D USBD_CUSTOM_HID_REPORT_DESC_SIZE=101
    -D CUSTOM_HID_EPIN_SIZE=64
    -D CUSTOM_HID_EPOUT_SIZE=64
    -D USBD_CUSTOMHID_OUTREPORT_BUF_SIZE=64
    -D CUSTOM_USBD_PID=0x57FF
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/libraries/USBDevice/inc"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/libraries/USBDevice/src"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Core/Src"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src"
